window.JOBS = {
 "generatedAt": "2026-08-04",
 "source": "전체 관심기업 채용페이지 (클릭 시 실시간 공고)",
 "note": "각 기업 채용페이지 직행 링크. ⭐표시는 ETCH/식각 직결 · 마감일 있는 곳은 D-day 관리",
 "items": [
  {"tracker":"SK하이닉스","cat":0,"company":"SK하이닉스","title":"하반기 기술사무직 신입 (양산기술·R&D공정)","url":"https://www.skcareers.com","start":"2026-08-20","deadline":"2026-08-26","region":"이천/청주","fav":true,"note":"⭐접수 8/20~26"},
  {"tracker":"삼성전자 DS","cat":0,"company":"삼성전자 DS","title":"하반기 3급 신입 공채","url":"https://www.samsungcareers.com/hr/","deadline":"2026-09-08","region":"기흥/화성/평택","fav":true,"note":"⭐9월초 예상"},
  {"tracker":"마이크론코리아","cat":0,"company":"Micron","title":"Process/Engineering 채용","url":"https://careers.micron.com/careers","region":"이천/청주","note":"외국계"},
  {"tracker":"매그나칩반도체","cat":0,"company":"Magnachip","title":"신입/경력 채용","url":"https://www.magnachip.com/careers/","region":"청주/구미"},
  {"tracker":"온세미","cat":0,"company":"onsemi","title":"Engineer 채용","url":"https://careers.onsemi.com/","region":"부천","note":"외국계"},
  {"tracker":"어플라이드머티어리얼즈","cat":1,"company":"Applied Materials","title":"Engineer 채용","url":"https://careers.appliedmaterials.com/careers","region":"화성/평택","note":"외국계 장비"},
  {"tracker":"ASML코리아","cat":1,"company":"ASML","title":"Engineer 채용","url":"https://www.asml.com/en/careers/find-a-job","region":"화성/평택","note":"외국계 노광"},
  {"tracker":"도쿄일렉트론코리아","cat":1,"company":"TEL","title":"Field/Process Engineer","url":"https://www.tel.com/careers/","region":"화성/평택","note":"외국계 장비"},
  {"tracker":"램리서치코리아","cat":1,"company":"Lam Research","title":"신입 FSE/Process (식각장비)","url":"https://careers.lamresearch.com","region":"용인/평택","fav":true,"note":"⭐ETCH 직결"},
  {"tracker":"원익IPS","cat":1,"company":"원익IPS","title":"공정개발·RF/플라즈마·부품개발","url":"https://recruit.wonik.com","region":"평택/용인","fav":true,"note":"⭐Dry Etcher 제조"},
  {"tracker":"주성엔지니어링","cat":1,"company":"주성엔지니어링","title":"신입/경력 (CVD/ALD 장비)","url":"https://jusung.career.greetinghr.com","region":"광주(경기)","note":"전공정 장비"},
  {"tracker":"PSK","cat":1,"company":"PSK","title":"신입/경력 (식각·세정 장비)","url":"https://www.psk-inc.com/recruit/","region":"화성","fav":true,"note":"⭐Dry Strip/식각"},
  {"tracker":"선익시스템","cat":1,"company":"Sunic System","title":"신입/경력 (OLED 증착장비)","url":"https://www.sunic.co.kr","region":"수원"},
  {"tracker":"참엔지니어링","cat":1,"company":"Charm Eng","title":"신입/경력 (검사·리페어 장비)","url":"https://www.charmeng.com","region":"수원"},
  {"tracker":"캐논코리아","cat":1,"company":"Canon Korea","title":"Engineer 채용","url":"https://www.canon-korea.co.kr","region":"안산","note":"외국계"},
  {"tracker":"유진테크","cat":1,"company":"유진테크","title":"플라즈마 제품개발 신입/경력","url":"https://eugenetech.co.kr/recruit/","region":"화성","fav":true,"note":"⭐플라즈마=식각핵심"},
  {"tracker":"테스","cat":1,"company":"TES","title":"신입/경력 (증착·식각 장비)","url":"https://www.tes.co.kr","region":"용인","fav":true,"note":"⭐PECVD/식각"},
  {"tracker":"케이씨텍","cat":1,"company":"KC Tech","title":"신입/경력 (CMP·세정 장비/소재)","url":"https://www.kctech.co.kr","region":"안성/용인","note":"장비+소재"},
  {"tracker":"이오테크닉스","cat":1,"company":"EO Technics","title":"신입/경력 (레이저 장비)","url":"https://www.eotechnics.com","region":"안양"},
  {"tracker":"GST","cat":1,"company":"GST","title":"신입/경력 (스크러버·칠러)","url":"https://www.gst-in.com","region":"천안"},
  {"tracker":"유니셈","cat":1,"company":"UNISEM","title":"신입/경력 (스크러버·칠러)","url":"https://www.unisem.co.kr","region":"화성"},
  {"tracker":"네패스","cat":2,"company":"nepes","title":"신입/경력 (패키징)","url":"https://www.nepes.co.kr/recruit","region":"청안/괴산"},
  {"tracker":"앰코테크놀로지코리아","cat":2,"company":"Amkor","title":"신입/경력 (패키징·테스트)","url":"https://www.amkor.com/careers/","region":"광주/인천","note":"외국계"},
  {"tracker":"한미반도체","cat":2,"company":"한미반도체","title":"신입/경력 (본더·후공정 장비)","url":"https://www.hanmisemi.com","region":"인천","note":"HBM TC본더"},
  {"tracker":"LB세미콘","cat":2,"company":"LB Semicon","title":"신입/경력 (범핑·테스트)","url":"https://www.lbsemicon.com","region":"음성"},
  {"tracker":"스태츠칩팩코리아","cat":2,"company":"STATS ChipPAC","title":"신입/경력 (패키징)","url":"https://www.statschippac.com/careers","region":"이천","note":"외국계"},
  {"tracker":"ASE코리아","cat":2,"company":"ASE Korea","title":"신입/경력 (패키징·테스트)","url":"https://www.aseglobal.com/en/careers/","region":"파주","note":"외국계"},
  {"tracker":"하나마이크론","cat":2,"company":"Hana Micron","title":"신입/경력 (패키징)","url":"https://www.hanamicron.com","region":"아산"},
  {"tracker":"두산테스나","cat":2,"company":"Doosan Tesna","title":"신입/경력 (테스트)","url":"https://career.doosan.com","region":"평택/용인"},
  {"tracker":"SFA반도체","cat":2,"company":"SFA반도체","title":"신입/경력 (패키징·테스트)","url":"https://www.sfareflow.com","region":"천안/부천"},
  {"tracker":"삼성전기","cat":3,"company":"삼성전기","title":"하반기 신입 (MLCC·기판)","url":"https://www.samsungcareers.com/hr/","region":"수원/부산","note":"삼성 계열"},
  {"tracker":"SK실트론","cat":3,"company":"SK실트론","title":"하반기 신입 (웨이퍼)","url":"https://www.skcareers.com","region":"구미","note":"SK 계열"},
  {"tracker":"동진쎄미켐","cat":3,"company":"동진쎄미켐","title":"신입/경력 (포토레지스트)","url":"https://www.dongjin.com","region":"화성/발안","fav":true,"note":"⭐식각/PR 소재"},
  {"tracker":"솔브레인","cat":3,"company":"Soulbrain","title":"신입/경력 (식각액·CMP슬러리)","url":"https://www.soulbrain.co.kr/recruit/","region":"공주/성남","fav":true,"note":"⭐식각액 소재"},
  {"tracker":"티씨케이","cat":3,"company":"TCK","title":"신입/경력 (SiC 부품)","url":"https://www.tckcorp.com","region":"안성","note":"식각 챔버부품"},
  {"tracker":"동우화인켐","cat":3,"company":"동우화인켐","title":"신입/경력 (전자재료)","url":"https://www.dwchem.co.kr","region":"평택/익산","note":"외국계(스미토모)"},
  {"tracker":"도레이첨단소재","cat":3,"company":"Toray","title":"신입/경력 (필름·소재)","url":"https://www.torayamk.com","region":"구미","note":"외국계"},
  {"tracker":"신에츠코리아","cat":3,"company":"Shin-Etsu","title":"Engineer 채용","url":"https://www.shinetsu.co.kr","region":"평택","note":"외국계"},
  {"tracker":"KCC","cat":3,"company":"KCC","title":"하반기 신입 (실리콘·소재)","url":"https://recruit.kcc.co.kr","region":"전국"},
  {"tracker":"LG화학","cat":3,"company":"LG화학","title":"하반기 신입 (첨단소재)","url":"https://apply.lgchem.com","region":"대전/오창","note":"LG 계열"},
  {"tracker":"롯데케미칼","cat":3,"company":"롯데케미칼","title":"하반기 신입","url":"https://job.lotte.co.kr","region":"대전/여수"},
  {"tracker":"서울반도체","cat":3,"company":"Seoul Semicon","title":"신입/경력 (LED)","url":"https://www.seoulsemicon.com/kr/company/Recruitment/","region":"안산"},
  {"tracker":"일진다이아몬드","cat":3,"company":"Iljin","title":"신입/경력 (초경소재)","url":"https://www.iljindiamond.co.kr","region":"음성"},
  {"tracker":"삼화콘덴서","cat":3,"company":"Samwha","title":"신입/경력 (콘덴서)","url":"https://www.samwha.com","region":"용인"},
  {"tracker":"SEMCNS","cat":3,"company":"SEMCNS","title":"신입/경력","url":"https://www.semcns.com","region":"안성"},
  {"tracker":"STM","cat":3,"company":"STM","title":"신입/경력","url":"https://www.stmc.co.kr","region":"평택"},
  {"tracker":"원익QnC","cat":3,"company":"원익QnC","title":"쿼츠개발·세정공정관리","url":"https://recruit.wonik.com","region":"구미/안성","fav":true,"note":"⭐쿼츠(식각챔버)"},
  {"tracker":"하나머티리얼즈","cat":3,"company":"Hana Materials","title":"신입/경력 (실리콘 부품)","url":"https://www.hanamaterials.com","region":"아산","note":"식각 챔버부품"},
  {"tracker":"코미코","cat":3,"company":"KoMiCo","title":"신입/경력 (세정·코팅)","url":"https://www.komico.com","region":"안성","fav":true,"note":"⭐부품 세정/코팅"},
  {"tracker":"디엔에프","cat":3,"company":"DNF","title":"신입/경력 (전구체)","url":"https://www.dnfsolution.com","region":"대전","note":"증착 전구체"},
  {"tracker":"미코","cat":3,"company":"MiCo","title":"신입/경력 (세라믹 부품)","url":"https://www.mico.kr","region":"안성"},
  {"tracker":"엠케이전자","cat":3,"company":"MK Electron","title":"신입/경력 (본딩와이어)","url":"https://www.mke.co.kr","region":"용인"},
  {"tracker":"삼성디스플레이","cat":4,"company":"삼성디스플레이","title":"하반기 신입","url":"https://www.samsungcareers.com/hr/","region":"아산/천안","note":"삼성 계열"},
  {"tracker":"LG디스플레이","cat":4,"company":"LG디스플레이","title":"하반기 신입","url":"https://apply.lgdisplay.com","region":"파주/구미","note":"LG 계열"},
  {"tracker":"LG에너지솔루션","cat":5,"company":"LG에너지솔루션","title":"하반기 신입 (진행중 다수)","url":"https://careers.lgensol.com","region":"오창/대전","fav":true,"note":"이차전지 대표"},
  {"tracker":"삼성SDI","cat":5,"company":"삼성SDI","title":"하반기 3급 신입 (생산·공정)","url":"https://www.samsungcareers.com/hr/","region":"기흥/천안/울산","fav":true,"note":"재료/화공 지원가능"},
  {"tracker":"SK온","cat":5,"company":"SK온","title":"하반기 신입","url":"https://www.skcareers.com","region":"서산/청주","note":"SK 계열"},
  {"tracker":"포스코퓨처엠","cat":5,"company":"POSCO Future M","title":"하반기 신입 (양극재·음극재)","url":"https://recruit.poscofuturem.com","region":"포항/광양","fav":true,"note":"양·음극재"},
  {"tracker":"에코프로비엠","cat":5,"company":"EcoPro BM","title":"신입/경력 (양극재)","url":"https://www.ecopro.co.kr/recruit","region":"청주/포항","fav":true,"note":"양극재"},
  {"tracker":"롯데에너지머티리얼즈","cat":5,"company":"Lotte Energy Materials","title":"신입/경력 (동박)","url":"https://job.lotte.co.kr","region":"익산"},
  {"tracker":"두산에너빌리티","cat":5,"company":"Doosan Enerbility","title":"하반기 신입","url":"https://career.doosan.com","region":"창원"},
  {"tracker":"두산퓨얼셀","cat":5,"company":"Doosan Fuel Cell","title":"신입/경력 (연료전지)","url":"https://career.doosan.com","region":"익산"},
  {"tracker":"한화큐셀","cat":5,"company":"Hanwha Qcells","title":"신입/경력 (태양광)","url":"https://www.hanwhain.com/web/careers/","region":"진천/음성"},
  {"tracker":"동원시스템즈","cat":5,"company":"Dongwon Systems","title":"신입/경력 (2차전지 소재)","url":"https://www.dongwonsystems.com","region":"아산"},
  {"tracker":"유진테크놀로지","cat":5,"company":"Eugene Tech","title":"신입/경력 (전지 부품)","url":"https://www.eugene-tech.com","region":"음성"},
  {"tracker":"델코","cat":5,"company":"Delkor","title":"신입/경력","url":"https://www.delkor.co.kr","region":"천안"},
  {"tracker":"엘앤에프","cat":5,"company":"L&F","title":"신입/경력 (양극재)","url":"https://www.landf.co.kr","region":"대구/구미","fav":true,"note":"양극재"},
  {"tracker":"에코프로머티리얼즈","cat":5,"company":"EcoPro Materials","title":"신입/경력 (전구체)","url":"https://www.ecopro.co.kr/recruit","region":"포항"},
  {"tracker":"SK아이이테크놀로지","cat":5,"company":"SKIET","title":"신입/경력 (분리막)","url":"https://www.skcareers.com","region":"청주/증평","note":"SK 계열 분리막"},
  {"tracker":"대주전자재료","cat":5,"company":"Daejoo","title":"신입/경력 (실리콘 음극재)","url":"https://www.daejoo.co.kr","region":"시흥","fav":true,"note":"실리콘 음극재"},
  {"tracker":"나노신소재","cat":5,"company":"ANP","title":"신입/경력 (CNT 도전재)","url":"https://www.anapro.com","region":"세종"},
  {"tracker":"성일하이텍","cat":5,"company":"SungEel HiTech","title":"신입/경력 (배터리 리사이클)","url":"https://www.seihitech.com","region":"군산"}
 ],
 "programs": [
  {"title":"SPTA 반도체공정기술교육원 — 8월 공정실습 (식각 포함)","host":"SPTA","url":"https://www.sptakorea.com","note":"⭐매월 예약 · ETCH 실습"},
  {"title":"서울대 반도체공동연구소(ISRC) 학부생 공정실습","host":"SNU ISRC","url":"https://isrc.snu.ac.kr","note":"8대공정 · 조기마감"},
  {"title":"한국반도체아카데미 하반기 무료교육","host":"KSA","url":"https://academy.ksia.or.kr","note":"무료 · 장비사 채용이벤트"},
  {"title":"나노종합기술원(NNFC) 공정·계측 교육","host":"NNFC","url":"https://www.nnfc.re.kr","note":"대전 · 상시"}
 ]
};
